=== Requirements ===

ZTM ticket price feature

==== Use case ====
As a passenger, I want to see on the ticket machine screen the price of the ticket based on the zones I am travelling in
and the discount I am eligible for so that I can know how much I need to pay.

Demo By Mentors
The ticket price is calculated based on the following rules:
— Ticket price is calculated based on zones travelled.
- City Zone 1: $3.25
— Countryside Zone 2: $5.50

Exercises for participants to implement what mentor did + requirements below

Exercise 1:
— Implement the ticket price calculation based on the rules above:

- Student discount: __30%__ off
- Senior discount: 50% off
- Free travel for children under 5


Next exercise for participants:
— Implement ticket validation.
The ticket machine should validate based on expiration date.
The ticket is valid for 1 hour after purchase
validation is blocked beacuse of ticket inspection in bus.
Program should throw an exception if the ticket is expired.
— If the ticket is expired
